# Generated by Django 4.2 on 2024-08-28 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='rating',
            new_name='discount_price',
        ),
    ]
